name: Build OpenWrt APK (Snapshot)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build packages via OpenWrt SDK
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: mediatek-filogic
          FEEDNAME: custom_packages
          V: s

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v6
        with:
          name: mediatek-filogic-packages
          path: bin/**/*.apk
